(function(b){b.fn.findFirstImage=function(){return this.first().find("img").andSelf().filter("img").first()};var g={defaults:{animation:"horizontal-push",animationSpeed:600,timer:!0,advanceSpeed:4E3,pauseOnHover:!1,startClockOnMouseOut:!1,startClockOnMouseOutAfter:1E3,directionalNav:!0,directionalNavRightText:"Right",directionalNavLeftText:"Left",captions:!0,captionAnimation:"fade",captionAnimationSpeed:600,resetTimerOnClick:!1,bullets:!1,bulletThumbs:!1,bulletThumbLocation:"",afterSlideChange:b.noop,
afterLoadComplete:b.noop,fluid:!0,centerBullets:!0,singleCycle:!1,slideNumber:!1,stackOnSmall:!1},activeSlide:0,numberSlides:0,orbitWidth:null,orbitHeight:null,locked:null,timerRunning:null,degrees:0,wrapperHTML:'<div class="orbit-wrapper" />',timerHTML:'<div class="timer"><span class="mask"><span class="rotator"></span></span><span class="pause"></span></div>',captionHTML:'<div class="orbit-caption"></div>',directionalNavHTML:'<div class="slider-nav hide-for-small"><span class="right"></span><span class="left"></span></div>',
bulletHTML:'<ul class="orbit-bullets"></ul>',slideNumberHTML:'<span class="orbit-slide-counter"></span>',init:function(a,c){var d,f=0,e=this;this.clickTimer=b.proxy(this.clickTimer,this);this.addBullet=b.proxy(this.addBullet,this);this.resetAndUnlock=b.proxy(this.resetAndUnlock,this);this.stopClock=b.proxy(this.stopClock,this);this.startTimerAfterMouseLeave=b.proxy(this.startTimerAfterMouseLeave,this);this.clearClockMouseLeaveTimer=b.proxy(this.clearClockMouseLeaveTimer,this);this.rotateTimer=b.proxy(this.rotateTimer,
this);this.options=b.extend({},this.defaults,c);"false"===this.options.timer&&(this.options.timer=!1);"false"===this.options.captions&&(this.options.captions=!1);"false"===this.options.directionalNav&&(this.options.directionalNav=!1);this.$element=b(a);this.$wrapper=this.$element.wrap(this.wrapperHTML).parent();this.$slides=this.$element.children("img, a, div, figure");this.$element.on("movestart",function(a){(a.distX>a.distY&&a.distX<-a.distY||a.distX<a.distY&&a.distX>-a.distY)&&a.preventDefault()});
this.$element.bind("orbit.next swipeleft",function(){e.shift("next")});this.$element.bind("orbit.prev swiperight",function(){e.shift("prev")});this.$element.bind("orbit.goto",function(a,b){e.shift(b)});this.$element.bind("orbit.start",function(){e.startClock()});this.$element.bind("orbit.stop",function(){e.stopClock()});d=this.$slides.filter("img");0===d.length?this.loaded():d.bind("imageready",function(){f+=1;f===d.length&&e.loaded()})},loaded:function(){this.$element.addClass("orbit").css({width:"1px",
height:"1px"});this.options.stackOnSmall&&this.$element.addClass("orbit-stack-on-small");this.$slides.addClass("orbit-slide");this.setDimentionsFromLargestSlide();this.updateOptionsIfOnlyOneSlide();this.setupFirstSlide();this.notifySlideChange();this.options.timer&&(this.setupTimer(),this.startClock());this.options.captions&&this.setupCaptions();this.options.directionalNav&&this.setupDirectionalNav();this.options.bullets&&(this.setupBulletNav(),this.setActiveBullet());this.options.afterLoadComplete.call(this);
Holder.run()},currentSlide:function(){return this.$slides.eq(this.activeSlide)},notifySlideChange:function(){if(this.options.slideNumber){var a=this.activeSlide+1+" of "+this.$slides.length;this.$element.trigger("orbit.change",{slideIndex:this.activeSlide,slideCount:this.$slides.length});void 0===this.$counter?(this.$counter=b(this.slideNumberHTML).html(a),this.$wrapper.append(this.$counter)):this.$counter.html(a)}},setDimentionsFromLargestSlide:function(){var a=this,c;a.$element.add(a.$wrapper).width(this.$slides.first().outerWidth());
a.$element.add(a.$wrapper).height(this.$slides.first().height());a.orbitWidth=this.$slides.first().outerWidth();a.orbitHeight=this.$slides.first().height();c=this.$slides.first().findFirstImage().clone();this.$slides.each(function(){var d=b(this),f=d.outerWidth(),d=d.height();f>a.$element.outerWidth()&&(a.$element.add(a.$wrapper).width(f),a.orbitWidth=a.$element.outerWidth());d>a.$element.height()&&(a.$element.add(a.$wrapper).height(d),a.orbitHeight=a.$element.height(),c=b(this).findFirstImage().clone());
a.numberSlides+=1});this.options.fluid&&("string"===typeof this.options.fluid&&(c=b("<img>").attr("data-src","holder.js/"+this.options.fluid)),a.$element.prepend(c),c.addClass("fluid-placeholder"),a.$element.add(a.$wrapper).css({width:"inherit"}),a.$element.add(a.$wrapper).css({height:"inherit"}),b(window).bind("resize",function(){a.orbitWidth=a.$element.outerWidth();a.orbitHeight=a.$element.height()}))},lock:function(){this.locked=!0},unlock:function(){this.locked=!1},updateOptionsIfOnlyOneSlide:function(){1===
this.$slides.length&&(this.options.directionalNav=!1,this.options.timer=!1,this.options.bullets=!1)},setupFirstSlide:function(){var a=this;this.$slides.first().css({"z-index":3,opacity:1}).fadeIn(function(){a.$slides.css({display:"block"})})},startClock:function(){var a=this;if(!this.options.timer)return!1;this.$timer.is(":hidden")?this.clock=setInterval(function(){a.$element.trigger("orbit.next")},this.options.advanceSpeed):(this.timerRunning=!0,this.$pause.removeClass("active"),this.clock=setInterval(this.rotateTimer,
this.options.advanceSpeed/180,!1))},rotateTimer:function(a){var b="rotate("+this.degrees+"deg)";this.degrees+=2;this.$rotator.css({"-webkit-transform":b,"-moz-transform":b,"-o-transform":b,"-ms-transform":b});180<this.degrees&&(this.$rotator.addClass("move"),this.$mask.addClass("move"));if(360<this.degrees||a)this.$rotator.removeClass("move"),this.$mask.removeClass("move"),this.degrees=0,this.$element.trigger("orbit.next")},stopClock:function(){if(this.options.timer)this.timerRunning=!1,clearInterval(this.clock),
this.$pause.addClass("active");else return!1},setupTimer:function(){this.$timer=b(this.timerHTML);this.$wrapper.append(this.$timer);this.$rotator=this.$timer.find(".rotator");this.$mask=this.$timer.find(".mask");this.$pause=this.$timer.find(".pause");this.$timer.click(this.clickTimer);this.options.startClockOnMouseOut&&(this.$wrapper.mouseleave(this.startTimerAfterMouseLeave),this.$wrapper.mouseenter(this.clearClockMouseLeaveTimer));this.options.pauseOnHover&&this.$wrapper.mouseenter(this.stopClock)},
startTimerAfterMouseLeave:function(){var a=this;this.outTimer=setTimeout(function(){a.timerRunning||a.startClock()},this.options.startClockOnMouseOutAfter)},clearClockMouseLeaveTimer:function(){clearTimeout(this.outTimer)},clickTimer:function(){this.timerRunning?this.stopClock():this.startClock()},setupCaptions:function(){this.$caption=b(this.captionHTML);this.$wrapper.append(this.$caption);this.setCaption()},setCaption:function(){var a=this.currentSlide().attr("data-caption"),c;if(!this.options.captions)return!1;
if(a){if(1>b.trim(b(a).text()).length)return!1;c=b(a).html();this.$caption.attr("id",a).html(c);switch(this.options.captionAnimation){case "none":this.$caption.show();break;case "fade":this.$caption.fadeIn(this.options.captionAnimationSpeed);break;case "slideOpen":this.$caption.slideDown(this.options.captionAnimationSpeed)}}else switch(this.options.captionAnimation){case "none":this.$caption.hide();break;case "fade":this.$caption.fadeOut(this.options.captionAnimationSpeed);break;case "slideOpen":this.$caption.slideUp(this.options.captionAnimationSpeed)}},
setupDirectionalNav:function(){var a=this,c=b(this.directionalNavHTML);c.find(".right").html(this.options.directionalNavRightText);c.find(".left").html(this.options.directionalNavLeftText);this.$wrapper.append(c);this.$wrapper.find(".left").click(function(){a.stopClock();a.options.resetTimerOnClick&&(a.rotateTimer(!0),a.startClock());a.$element.trigger("orbit.prev")});this.$wrapper.find(".right").click(function(){a.stopClock();a.options.resetTimerOnClick&&(a.rotateTimer(!0),a.startClock());a.$element.trigger("orbit.next")})},
setupBulletNav:function(){this.$bullets=b(this.bulletHTML);this.$wrapper.append(this.$bullets);this.$slides.each(this.addBullet);this.$element.addClass("with-bullets");this.options.centerBullets&&this.$bullets.css("margin-left",-this.$bullets.outerWidth()/2)},addBullet:function(a,c){var d=b("<li>"+(a+1)+"</li>"),f,e=this;this.options.bulletThumbs&&(f=b(c).attr("data-thumb"))&&d.addClass("has-thumb").css({background:"url("+this.options.bulletThumbLocation+f+") no-repeat"});this.$bullets.append(d);
d.data("index",a);d.click(function(){e.stopClock();e.options.resetTimerOnClick&&(e.rotateTimer(!0),e.startClock());e.$element.trigger("orbit.goto",[d.data("index")])})},setActiveBullet:function(){if(this.options.bullets)this.$bullets.find("li").removeClass("active").eq(this.activeSlide).addClass("active");else return!1},resetAndUnlock:function(){this.$slides.eq(this.prevActiveSlide).css({"z-index":1});this.unlock();this.options.afterSlideChange.call(this,this.$slides.eq(this.prevActiveSlide),this.$slides.eq(this.activeSlide))},
shift:function(a){var c=a;this.prevActiveSlide=this.activeSlide;if(this.prevActiveSlide==c||"1"==this.$slides.length)return!1;this.locked||(this.lock(),"next"==a?(this.activeSlide++,this.activeSlide==this.numberSlides&&(this.activeSlide=0)):"prev"==a?(this.activeSlide--,0>this.activeSlide&&(this.activeSlide=this.numberSlides-1)):(this.activeSlide=a,this.prevActiveSlide<this.activeSlide?c="next":this.prevActiveSlide>this.activeSlide&&(c="prev")),this.setActiveBullet(),this.notifySlideChange(),this.$slides.eq(this.prevActiveSlide).css({"z-index":2}),
"fade"==this.options.animation&&(this.$slides.eq(this.activeSlide).css({opacity:0,"z-index":3}).animate({opacity:1},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).animate({opacity:0},this.options.animationSpeed)),"horizontal-slide"==this.options.animation&&("next"==c&&this.$slides.eq(this.activeSlide).css({left:this.orbitWidth,"z-index":3}).css("opacity",1).animate({left:0},this.options.animationSpeed,this.resetAndUnlock),"prev"==c&&this.$slides.eq(this.activeSlide).css({left:-this.orbitWidth,
"z-index":3}).css("opacity",1).animate({left:0},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).css("opacity",0)),"vertical-slide"==this.options.animation&&("prev"==c&&(this.$slides.eq(this.activeSlide).css({top:this.orbitHeight,"z-index":3}).css("opacity",1).animate({top:0},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).css("opacity",0)),"next"==c&&this.$slides.eq(this.activeSlide).css({top:-this.orbitHeight,"z-index":3}).css("opacity",
1).animate({top:0},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).css("opacity",0)),"horizontal-push"==this.options.animation&&("next"==c&&(this.$slides.eq(this.activeSlide).css({left:this.orbitWidth,"z-index":3}).animate({left:0,opacity:1},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).animate({left:-this.orbitWidth},this.options.animationSpeed,"",function(){b(this).css({opacity:0})})),"prev"==c&&(this.$slides.eq(this.activeSlide).css({left:-this.orbitWidth,
"z-index":3}).animate({left:0,opacity:1},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).animate({left:this.orbitWidth},this.options.animationSpeed,"",function(){b(this).css({opacity:0})}))),"vertical-push"==this.options.animation&&("next"==c&&(this.$slides.eq(this.activeSlide).css({top:-this.orbitHeight,"z-index":3}).css("opacity",1).animate({top:0,opacity:1},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).css("opacity",
0).animate({top:this.orbitHeight},this.options.animationSpeed,"")),"prev"==c&&(this.$slides.eq(this.activeSlide).css({top:this.orbitHeight,"z-index":3}).css("opacity",1).animate({top:0},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).css("opacity",0).animate({top:-this.orbitHeight},this.options.animationSpeed))),this.setCaption());this.$slides.last()&&this.options.singleCycle&&this.stopClock()}};b.fn.orbit=function(a){return this.each(function(){b.extend({},
g).init(this,a)})}})(jQuery);(function(b){function g(a,d){var f=b(a);f.bind("load.imageready",function(){d.apply(a,arguments);f.unbind("load.imageready")})}var a={};b.event.special.imageready={setup:function(b){a=b||a},add:function(c){var d=b(this),f;1===this.nodeType&&("img"===this.tagName.toLowerCase()&&""!==this.src)&&(a.forceLoad?(f=d.attr("src"),d.attr("src",""),g(this,c.handler),d.attr("src",f)):this.complete||4===this.readyState?c.handler.apply(this,arguments):g(this,c.handler))},teardown:function(){b(this).unbind(".imageready")}}})(jQuery);
var Holder=Holder||{};
(function(b,g){function a(a){a=a.match(/^(\W)?(.*)/);a=document["getElement"+(a[1]?"#"==a[1]?"ById":"sByClassName":"sByTagName")](a[2]);var b=[];null!=a&&(a.length?b=a:0==a.length?b=a:b=[a]);return b}function c(a,b){var c={},d;for(d in a)c[d]=a[d];for(var h in b)c[h]=b[h];return c}function d(a,b,c){var d=[b.height,b.width].sort(),h=Math.round(d[1]/16),d=Math.round(d[0]/16),h=Math.max(c.size,h);e.width=b.width;e.height=b.height;a.textAlign="center";a.textBaseline="middle";a.fillStyle=c.background;
a.fillRect(0,0,b.width,b.height);a.fillStyle=c.foreground;a.font="bold "+h+"px sans-serif";var f=c.text?c.text:b.width+"x"+b.height;1<Math.round(a.measureText(f).width)/b.width&&(h=Math.max(d,c.size));a.font="bold "+h+"px sans-serif";a.fillText(f,b.width/2,b.height/2,b.width);return e.toDataURL("image/png")}var f=!1,e=document.createElement("canvas");if(e.getContext)if(0>e.toDataURL("image/png").indexOf("data:image/png"))f=!0;else var z=e.getContext("2d");else f=!0;var s={domain:"holder.js",images:"img",
themes:{gray:{background:"#eee",foreground:"#aaa",size:12},social:{background:"#3a5a97",foreground:"#fff",size:12},industrial:{background:"#434A52",foreground:"#C2F200",size:12}}};b.flags={dimensions:{regex:/([0-9]+)x([0-9]+)/,output:function(a){a=this.regex.exec(a);return{width:+a[1],height:+a[2]}}},colors:{regex:/#([0-9a-f]{3,})\:#([0-9a-f]{3,})/i,output:function(a){a=this.regex.exec(a);return{size:s.themes.gray.size,foreground:"#"+a[2],background:"#"+a[1]}}},text:{regex:/text\:(.*)/,output:function(a){return this.regex.exec(a)[1]}}};
for(var l in b.flags)b.flags[l].match=function(a){return a.match(this.regex)};b.add_theme=function(a,c){null!=a&&null!=c&&(s.themes[a]=c);return b};b.add_image=function(c,d){var f=a(d);if(f.length)for(var e=0,h=f.length;e<h;e++){var g=document.createElement("img");g.setAttribute("data-src",c);f[e].appendChild(g)}return b};b.run=function(e){e=c(s,e);for(var g=a(e.images),k=g.length,n=0;n<k;n++){var h=s.themes.gray,q=g[n].getAttribute("data-src")||g[n].getAttribute("src");if(~q.indexOf(e.domain)){var p=
!1,l=null,r=null,m=q.substr(q.indexOf(e.domain)+e.domain.length+1).split("/");sl=m.length;for(j=0;j<sl;j++)b.flags.dimensions.match(m[j])?(p=!0,l=b.flags.dimensions.output(m[j])):b.flags.colors.match(m[j])?h=b.flags.colors.output(m[j]):e.themes[m[j]]?h=e.themes[m[j]]:b.flags.text.match(m[j])&&(r=b.flags.text.output(m[j]));p&&(g[n].setAttribute("data-src",q),q=l.width+"x"+l.height,g[n].setAttribute("alt",r?r:h.text?h.text+" ["+q+"]":q),g[n].style.backgroundColor=h.background,h=r?c(h,{text:r}):h,f||
g[n].setAttribute("src",d(z,l,h)))}}return b};var v=function(){b.run()},w=!1;l=!0;var k=g.document,x=k.documentElement,u=k.addEventListener?"addEventListener":"attachEvent",A=k.addEventListener?"removeEventListener":"detachEvent",t=k.addEventListener?"":"on",p=function(a){("readystatechange"!=a.type||"complete"==k.readyState)&&(("load"==a.type?g:k)[A](t+a.type,p,!1),!w&&(w=!0)&&v.call(g,null))},y=function(){try{x.doScroll("left")}catch(a){setTimeout(y,50);return}p("poll")};if("complete"==k.readyState)v.call(g,
"lazy");else{if(k.createEventObject&&x.doScroll){try{l=!g.frameElement}catch(B){}l&&y()}k[u](t+"DOMContentLoaded",p,!1);k[u](t+"readystatechange",p,!1);g[u](t+"load",p,!1)}})(Holder,window);