(function(a){jQuery.foundation=jQuery.foundation||{};jQuery.foundation.customForms=jQuery.foundation.customForms||{};a.foundation.customForms.appendCustomMarkup=function(c){function b(b,c){var g=a(c).hide(),f=g.attr("type"),d=g.next("span.custom."+f);0===d.length&&(d=a('<span class="custom '+f+'"></span>').insertAfter(g));d.toggleClass("checked",g.is(":checked"));d.toggleClass("disabled",g.is(":disabled"))}c=a.extend({disable_class:"js-disable-custom"},c);a("form.custom input:radio[data-customforms!=disabled]").each(b);
a("form.custom input:checkbox[data-customforms!=disabled]").each(b);a("form.custom select[data-customforms!=disabled]").each(function(c,b){var g={tmp:[],hidden:null,adjust:function(b){var c=this;c.hidden=b.parents().andSelf().filter(":hidden");c.hidden.each(function(){var b=a(this);c.tmp.push(b.attr("style"));b.css({visibility:"hidden",display:"block"})})},reset:function(){var b=this;b.hidden.each(function(c){var d=a(this);c=b.tmp[c];void 0===c?d.removeAttr("style"):d.attr("style",c)});b.tmp=[];b.hidden=
null}},f=a(b),d=f.next("div.custom.dropdown"),h=d.find("ul");d.find(".current");d.find(".selector");var l=f.find("option"),j=l.filter(":selected"),k=0,m="",n,p=!1;f.hasClass("no-custom")||(0===d.length?(d=f.hasClass("small")?"small":f.hasClass("medium")?"medium":f.hasClass("large")?"large":f.hasClass("expand")?"expand":"",d=a('<div class="'+["custom dropdown",d].join(" ")+'"><a href="#" class="selector"></a><ul /></div>"'),d.find(".selector"),h=d.find("ul"),m=l.map(function(){return"<li>"+a(this).html()+
"</li>"}).get().join(""),h.append(m),p=d.prepend('<a href="#" class="current">'+j.html()+"</a>").find(".current"),f.after(d).hide()):(m=l.map(function(){return"<li>"+a(this).html()+"</li>"}).get().join(""),h.html("").append(m)),d.toggleClass("disabled",f.is(":disabled")),n=h.find("li"),l.each(function(b){this.selected&&(n.eq(b).addClass("selected"),p&&p.html(a(this).html()))}),h.css("width","inherit"),d.css("width","inherit"),d.is(".small, .medium, .large, .expand")||(d.addClass("open"),g.adjust(h),
k=n.outerWidth()>k?n.outerWidth():k,g.reset(),d.removeClass("open"),d.width(k+18),h.width(k+16)))})};var j=function(c){var b=c.prev(),a=b[0];!1===b.is(":disabled")&&(a.checked=a.checked?!1:!0,c.toggleClass("checked"),b.trigger("change"))},q=function(a){var b=a.prev(),e=b.closest("form.custom"),r=b[0];!1===b.is(":disabled")&&(e.find('input:radio[name="'+b.attr("name")+'"]').next().not(a).removeClass("checked"),a.hasClass("checked")||a.toggleClass("checked"),r.checked=a.hasClass("checked"),b.trigger("change"))};
a(document).on("click","form.custom span.custom.checkbox",function(c){c.preventDefault();c.stopPropagation();j(a(this))});a(document).on("click","form.custom span.custom.radio",function(c){c.preventDefault();c.stopPropagation();q(a(this))});a(document).on("change","form.custom select[data-customforms!=disabled]",function(){var c=a(this),b=0,e=c.next();$options=c.find("option");e.find("ul").html("");$options.each(function(){$li=a("<li>"+a(this).html()+"</li>");e.find("ul").append($li)});$options.each(function(b){this.selected&&
(e.find("li").eq(b).addClass("selected"),e.find(".current").html(a(this).html()))});e.removeAttr("style").find("ul").removeAttr("style");e.find("li").each(function(){e.addClass("open");a(this).outerWidth()>b&&(b=a(this).outerWidth());e.removeClass("open")});e.css("width",b+18+"px");e.find("ul").css("width",b+16+"px")});a(document).on("click","form.custom label",function(c){var b=a("#"+a(this).attr("for")+"[data-customforms!=disabled]");0!==b.length&&("checkbox"===b.attr("type")?(c.preventDefault(),
c=a(this).find("span.custom.checkbox"),j(c)):"radio"===b.attr("type")&&(c.preventDefault(),c=a(this).find("span.custom.radio"),q(c)))});a(document).on("click","form.custom div.custom.dropdown a.current, form.custom div.custom.dropdown a.selector",function(c){var b=a(this).closest("div.custom.dropdown"),e=b.prev();c.preventDefault();a("div.dropdown").removeClass("open");if(!1===e.is(":disabled"))return b.toggleClass("open"),b.hasClass("open")?a(document).bind("click.customdropdown",function(){b.removeClass("open");
a(document).unbind(".customdropdown")}):a(document).unbind(".customdropdown"),!1});a(document).on("click","form.custom div.custom.dropdown li",function(c){var b=a(this),e=b.closest("div.custom.dropdown"),j=e.prev(),g=0;c.preventDefault();c.stopPropagation();a("div.dropdown").removeClass("open");b.closest("ul").find("li").removeClass("selected");b.addClass("selected");e.removeClass("open").find("a.current").html(b.html());b.closest("ul").find("li").each(function(a){b[0]==this&&(g=a)});j[0].selectedIndex=
g;j.trigger("change")});a.fn.foundationCustomForms=a.foundation.customForms.appendCustomMarkup})(jQuery);